name: moniz
description: A new Flutter project.
publish_to: "none"

version: 1.7.1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  animated_size_and_fade: ^5.1.1
  animations: ^2.0.11
  collection: ^1.19.0
  currency_picker: ^2.0.21
  device_info_plus: ^11.2.1
  drift: ^2.24.0
  dynamic_color: ^1.7.0
  envied: ^1.1.0
  envied_generator: ^1.1.0
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_compass: ^0.8.1
  flutter_iconpicker: ^4.0.1
  flutter_map: ^8.1.1
  flutter_map_animations: ^0.9.0
  flutter_map_location_marker: ^10.1.0
  flutter_map_marker_cluster: ^1.4.0
  flutter_native_splash: ^2.4.4
  flutter_riverpod: ^3.0.0-dev.17
  fluttertoast: ^8.2.10
  freezed: ^3.0.6
  geolocator: ^14.0.0
  get_storage: ^2.1.1
  graphic: ^2.5.1
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.2.0
  http: ^1.3.0
  intl: ^0.20.2
  introduction_screen: ^3.1.14
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  location: ^8.0.0
  numeral: ^3.1.1
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  posthog_flutter: ^5.0.0
  riverpod_annotation: ^3.0.0-dev.17
  scrollable_positioned_list: ^0.3.8
  sentry_flutter: ^9.6.0
  share_plus: ^11.0.0
  sqlite3_flutter_libs: ^0.5.29
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2
  window_manager: ^0.5.1
dependency_overrides:
  flutter_map_marker_cluster:
    git: https://github.com/matteomrz/flutter_map_marker_cluster.git

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.8.0
  drift_dev: ^2.24.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.8.2
  integration_test:
    sdk: flutter
  lint: ^2.3.0
  patrol: ^3.14.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17

flutter_native_splash:
  # ? Insists on giving me blurry icons
  color: "#ffffff"
  branding: assets/coin4.png
  color_dark: "#212121"
  android: true
  ios: false
  web: false
  android_12:
    image: assets/coin4.png
    icon_background_color: "#ffffff"
    image_dark: assets/coin4.png
    icon_background_color_dark: "#212121"

flutter_launcher_icons:
  android: true
  image_path: "assets/coin4.png"
  adaptive_icon_background: "#212121"
  adaptive_icon_foreground: "assets/coin4_adaptive.png"
  adaptive_icon_foreground_inset: 0
  adaptive_icon_monochrome: "assets/coin4_mono.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  fonts:
    - family: VictorMono
      fonts:
        - asset: fonts/VM/VictorMono-Regular.otf
        - asset: fonts/VM/VictorMono-SemiBold.otf
          weight: 800
  assets:
    - assets/coin4.png
